### ISSUE TITLE
大神组件传值的一个问题

### ISSUE THREAD

**Issue by chaihongjun** [bailicangdu/vue2-happyfri#101]
在 /page/home/index.vue 这个组件里面
给子组件 传值  请问

`
<itemcontainer father-component="home"></itemcontainer>
`

这个home 代表的是什么。 子组件itemcontainer通过fathercomponent属性接收的是什么值呢？

**Comment by MasonEast** [comment]
这个属性应该是主要用来判断的，在子组件created的时候，进行判断，如果是该属性是home，则初始化信息。

**Comment by chaihongjun** [comment]
@MasonEast  谢谢，是的，后面仔细看了一下。之前习惯思维是父要传子数据，这里只是一个固定的字符串"home" 判断是不是首页,包括后面的"item"
