### ISSUE TITLE
计算结果不对

### ISSUE THREAD

**Issue by haoxl3** [bailicangdu/vue2-happyfri#11]
答完题后，每次的得分都是20分，发现你在score/index.vue中的created()方法中给score赋值为20，难道不应该是前一个页面传过来，或者用vuex把score也当作状态来管理吗？

**Comment by bailicangdu** [comment]
纯粹的vue流程演示

**Comment by bailicangdu** [comment]
本身就是作为一个vue demo，掺杂其他的逻辑会浪费大家的时间

**Comment by skyflysun** [comment]
作者没有写那个逻辑，我在他的基础上改写了加分的计算
https://github.com/skyflysun/vue-vuex

**Comment by Mcqueengit** [comment]
@skyflysun 你能简单说一下你改的逻辑是代码的哪一部分吗
@haoxl3 说的是什么意思，意思是：不管每次选什么选项，最后的得分都是20分吗？如果是这样的话，作者已经实现选择不同的选项，能够得到相对应的分数了

**Comment by assmdx** [comment]
@bailicangdu 代码中是不是没有题目内容部分..？
