### ISSUE TITLE
内容不显示

### ISSUE THREAD

**Issue by PhoenixLeeSin** [bailicangdu/vue2-happyfri#121]
在main.js 下 如果不写
`
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')
`
中的 render: h => h(App) ，那么不会显示任何内容，大佬这是啥问题啊 
![image](https://user-images.githubusercontent.com/20637153/145161309-ff332267-e4db-4032-a61f-67f8e3f14404.png)

**Comment by kokakyo** [comment]
收到。

**Comment by bailicangdu** [comment]
因为render方法就是用来显示的呀

**Comment by PhoenixLeeSin** [comment]
@bailicangdu  我下载完代码 看你的里面没写啊

**Comment by bailicangdu** [comment]
版本不同吧

**Comment by PhoenixLeeSin** [comment]
我刚开始学习 不是很懂 我看你用的vue 2.1.0  我用的2.5.2 不清楚是不是这个原因
