### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by sereinof** [bailicangdu/vue2-happyfri#122]
-

**Comment by kokakyo** [comment]
收到。

**Comment by all-of-meup** [comment]
> 这个项目的有些依赖似乎是很久以前的版本，导致现在执行npm install的时候会报各种依赖混乱的错误，不知有没有大佬解答一下下啊。
执行 yarn

**Comment by kokakyo** [comment]
收到。

**Comment by 100PerFe** [comment]
> > 这个项目的有些依赖似乎是很久以前的版本，导致现在执行npm install的时候会报各种依赖混乱的错误，不知有没有大佬解答一下下啊。
> > 执行 yarn

有效果，不过不知道大家运行界面都这么丑[截图](https://s1.328888.xyz/2022/06/15/paQZv.png)
应该是适应手机屏幕。

**Comment by kokakyo** [comment]
收到。

**Comment by sereinof** [comment]
>
