### ISSUE TITLE
确实很适合初学者，但是代码style有些小意见

### ISSUE THREAD

**Issue by kylezhang** [bailicangdu/vue2-happyfri#2]
### 如下图，代码中既有空格键，也有tab键，不统一，对于有代码洁癖的人，怪难受的，哈哈
![image](https://cloud.githubusercontent.com/assets/3679798/23640677/275534d4-032a-11e7-874e-5997ba9f9908.png)

**Comment by asd1245dss** [comment]
@kylezhang 作者用editorconfig作了缩进的规范了，你可以安装插件来支持
![qq 20170311140453](https://cloud.githubusercontent.com/assets/2149974/23821095/b7e9db1c-0663-11e7-8535-201aeb6a990a.png)

**Comment by kylezhang** [comment]
OK
