### ISSUE TITLE
咨询一下rem.js导入

### ISSUE THREAD

**Issue by yuanyuanyuan** [bailicangdu/vue2-happyfri#26]
你好,请问在main.js里面导入`import './config/rem'`这个是怎么生效的呢?
因为我看到里面并没有export,vue实例化的时候是怎么使用得到这种导入的呢?谢谢

**Comment by lqh21** [comment]
vue不写后缀也是默认加载的

**Comment by liwuwuzhi** [comment]
'./style/common' 和 './config/rem' 是在 main.js 导入就会自动生效？还是因为在其他地方做了配置？
