### ISSUE TITLE
为什么点开happyfri文件夹里面的css文件还有js文件都是压缩后的状态

### ISSUE THREAD

**Issue by yangpeijia** [bailicangdu/vue2-happyfri#27]
大大，是我打开的方式不对吗？本人小白，刚接触vue，求解。

**Comment by bailicangdu** [comment]
那是发布状态，压缩体积，打开需要服务器环境

**Comment by yangpeijia** [comment]
好的，谢谢大大。还有一个问题就是为什么会有license文件，这个是发布必须的吗？如何生成？我看vue-cli里面是没有这个文件的。

**Comment by bailicangdu** [comment]
license是开源项目的协议，声明项目可以被怎样使用，这个项目是MIT，意思是可以拿去做任何事情。我的另外几个项目有些使用GPL协议，限制的条件就多了

**Comment by yangpeijia** [comment]
好的，我看到router.js 里大大在children的component有一个r的参数，这个参数是什么意思？因为我在网上也找不到r(require())相关的解释。

**Comment by yangpeijia** [comment]
我知道了，这个是懒加载，我在官方文档找到解释了。

**Comment by yangpeijia** [comment]
大大，我还有一个问题要请教就是实际开发中，我们编写每一个组件的时候要怎么去预览他的效果呢？难道要等所有组件都完成打包了再看？
