### ISSUE TITLE
运行dev直接打包了为什么

### ISSUE THREAD

**Issue by JangYB** [bailicangdu/vue2-happyfri#30]
![image](https://user-images.githubusercontent.com/21301544/28563288-15807358-7158-11e7-8968-13c0aa127f8a.png)

直接打包了？为什么没运行啊

**Comment by sicmu** [comment]
在浏览器直接输入http://localhost:8080就可以访问。不过这是怎么打包的啊。看提示是用webpack。但在项目里又没有看到webpack.config.js这个配置文件啊。真不明白。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
