### ISSUE TITLE
 npm run dev 之后 页面只有一图片 内容部分全没有啊？ 求指导

### ISSUE THREAD

**Issue by Candy2017** [bailicangdu/vue2-happyfri#31]

**Comment by matchless5233** [comment]
@Candy2017  切换到项目的目录再运行即可。

**Comment by Joyeuxman** [comment]
@matchless5233 能说的通俗点吗？

**Comment by Joyeuxman** [comment]
![default](https://user-images.githubusercontent.com/21262781/29483007-6cf8853c-84cf-11e7-95de-09743be316a1.png)

**Comment by matchless5233** [comment]
@Joyeuxman ** 最简单的办法：**
1 删除掉原来的项目；
2 重新客隆项目到本地  `git clone https://github.com/bailicangdu/vue2-happyfri.git` 。。。喝茶等待下载完成
3 切换到项目的目录，命令是`npm install` 等待安装完成
4 如果上面都没问题，那么久可以运行这个命令了 `npm run dev`
5 在浏览器中输入 控制台显示的地址，例如：`http://localhost:8088`

**Comment by Joyeuxman** [comment]
非常感谢你的帮助。
我按照你的步骤执行了一遍，还是同样的问题，我觉得是浏览器问题，尝试了几个浏览器后，依旧如此。
最后才发现这个项目必须切到手机模式下，不然页面显示异常。尴尬。。。
再次对你的帮助表示感谢，国人程序员都像你的话，那呼哧呼哧都能干过谷歌、微软了。哈哈。
![default](https://user-images.githubusercontent.com/21262781/29647929-4ef1297a-88be-11e7-8b07-f4356699cf57.png)

**Comment by zongwu0913** [comment]
同问啊，问也是这样！楼主有解决吗？

**Comment by xiaojiandong** [comment]
1. 切换到项目的目录，命令是npm install 等待安装完成
2. 如果上面都没问题，那么久可以运行这个命令了 npm run dev
3. 在浏览器中输入 控制台显示的地址，例如：http://localhost:8088
这几部我都完成了，切换到手机模式，依然没东西呈现 ...
@matchless5233 @Candy2017 @Joyeuxman 
![1507876452 1](https://user-images.githubusercontent.com/11863236/31533185-b8b4ef0e-b023-11e7-9b25-45c89f606da1.jpg)

**Comment by zhoubhin** [comment]
@xiaojiandong  大兄弟，端口是8088，要看命令行里显示的端口号。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
