### ISSUE TITLE
store 在子组建中找不到

### ISSUE THREAD

**Issue by DavidTiger** [bailicangdu/vue2-happyfri#36]
刚开始学习vue,下载这个demo，自己照着写了一个，
在子组建中的定义
![image](https://user-images.githubusercontent.com/11530030/31040947-5dcf74ea-a553-11e7-9f2a-0016a05d2bb2.png)
store中的定义
![image](https://user-images.githubusercontent.com/11530030/31040957-812f0266-a553-11e7-8f82-bc8e4d4ba69e.png)
运行的时候报这个错误

应该是再子组建中找不到

**Comment by DavidTiger** [comment]
提示这个：vue.esm.js?101b:476 [Vue warn]: Property or method "itemDetail" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
