### ISSUE TITLE
刚开始看vue2

### ISSUE THREAD

**Issue by bryant-shuai** [bailicangdu/vue2-happyfri#4]
npm run dev 之后浏览器没有反应，启动不了，怎么解决

**Comment by asd1245dss** [comment]
@bryant-shuai 你检查依赖是不是都安装上了
![image](https://cloud.githubusercontent.com/assets/2149974/23821019/00f7bc9a-0662-11e7-8e36-d3e20ffb4b28.png)

**Comment by bryant-shuai** [comment]
解决了，但是不会自启，需要我在地址栏手动输入8088，“建议你熟悉完node、npm、webpack之后再来看这个demo。”这个三块只会用，简单的使用

**Comment by bryant-shuai** [comment]
谢谢啦 @asd1245dss

**Comment by mqyxgwk8135156** [comment]
怎么解决的  我运行npm run dev 后报错

**Comment by mqyxgwk8135156** [comment]
![qw](https://user-images.githubusercontent.com/20755391/27372264-93b37a4a-5696-11e7-943b-aee171afa85f.png)
npm run dev   就报错  求教

**Comment by bailicangdu** [comment]
8088端口是不是被占用了

**Comment by mqyxgwk8135156** [comment]
是端口被占用的问题  谢谢

**Comment by pkwenda** [comment]
![image](https://user-images.githubusercontent.com/14212375/28462266-0cf78b9e-6e4d-11e7-81d6-1d02466db427.png)
各位大佬好，请教一下，build文件中的文件我可以一路debug到util到webpack，但是main.js和一些vue的js文件我怎么debug？我在node debug main.js没有反应,是vue只能在前端debug么？刚接触
@bailicangdu @asd1245dss
