### ISSUE TITLE
main.js 中 引入common.less 出现报错信息

### ISSUE THREAD

**Issue by xiangkun123** [bailicangdu/vue2-happyfri#41]
新建了一个项目，同样在main中引入common.js，为什么在main.js 中 引入 import './assets/style/common.less' 出现如下报错信息：
This relative module was not found:
* ./assets/style/common in ./src/main.js，要先安装什么模块才能这样引用吗？

**Comment by bailicangdu** [comment]
地址不对吧

**Comment by xiangkun123** [comment]
因为我是把images 和 style 文件夹都放到 assets 的目录下了，然后我也在install 了less 和在 webpack.base.conf.js 下添加了`{
        test: /\.less$/,
        loader: 'css-loader',
        options: {
          importLoaders: 1
        }
      }` 配置，但还是报错，但是我在 App.vue 的style下引用 @import './assets/style/common'; 就没有报错，不知道啥原因

**Comment by bailicangdu** [comment]
我觉得还是地址的问题，js和css引入图片地址的相对路径不一样，js是根据html地址，css是根据自身

**Comment by Anlao-c** [comment]
兄弟，你解决了吗，我也遇到了相同的问题。感觉是cli的版本问题，我的文件夹数量不相同

**Comment by xiangkun123** [comment]
@Anlao-c 在main.js中引入有两种方法可以解决。
第一种就是通过AMD方式来引入less：
require('!style-loader!css-loader!less-loader!./assets/style/test.less')；不过这种写法在你打包项目的时候可能要配置webpack相关内容；
第二种就是我在上面提到的，
import './assets/style/common.less';；原来由于我们下载的vue-cli本身自带的build文件夹下utils.js文件里面已经添加了less、css等等的样式配置，所以我们不用在webpack.base.conf.js 里添加test了，否则会报错。也就是说你直接install 了less，less-loader后直接引用样式就好了，相关的配置不用添加；

**Comment by onceFlycc** [comment]
@xiangkun123 兄弟你的解决了吗，估计是vue-cli版本问题，自己初始话的vue项目，一直报这错

**Comment by Anlao-c** [comment]
我能说一下吗。如果只是想运行这个项目的话，大可以把.less文件的引用语句屏了

**Comment by onceFlycc** [comment]
import './style/common.less'  这样就可以，js里import要加后缀

**Comment by Anlao-c** [comment]
能解决就好，不然我担心你晚上会睡不好觉的😢

**Comment by xiangkun123** [comment]
@onceFlycc 兄弟解决了吗？大晚上忙活着，没看到。这应该不是版本的问题吧，我试过几次都可以

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by dy-GitHub** [comment]
你们的这个问题解决了吗？上述几种都试了，依旧不行

**Comment by aaaxiu** [comment]
同样求问

**Comment by aaaxiu** [comment]
@dy-GitHub  上面onceFlycc的是正解, "import './style/common.less' 这样就可以，js里import要加后缀", 有一点要补充, 加了后缀之后还报错是因为common.less里面有一个样式调用了背景图片, 背景图片找不到报错, 把images文件夹一起放进来就好了
