### ISSUE TITLE
npm run build no such file or directory:static/*

### ISSUE THREAD

**Issue by wuwenyuan111** [bailicangdu/vue2-happyfri#44]
npm run build

> happyfri@1.0.2 build G:\workplace\WebStorm\vue2-happyfri
> node build/build.js

cp: no such file or directory: static/*
Hash: 279e8632ca3d04732614
Version: webpack 1.15.0
Time: 4519ms
                                      Asset       Size  Chunks             Chunk Names
 static/js/home.abe9f43ebc69913271f5.min.js    29.2 kB    1, 3  [emitted]  home
                         static/img/1-1.jpg     144 kB          [emitted]
                         static/img/4-1.jpg     193 kB          [emitted]
                         static/img/4-2.png    14.2 kB          [emitted]
                         static/img/4-4.png    10.4 kB          [emitted]
 static/js/item.b0390b470966316eaf4e.min.js    29.2 kB    0, 3  [emitted]  item
                         static/img/1-2.png    25.5 kB          [emitted]
static/js/score.1bf2ac51530fa17b0b12.min.js    21.4 kB    2, 3  [emitted]  score
                      static/js/manifest.js  962 bytes       3  [emitted]  manifest
                        static/js/vendor.js     153 kB    4, 3  [emitted]  vendor
                           static/js/app.js    6.25 kB    5, 3  [emitted]  app
                         static/css/app.css  970 bytes    5, 3  [emitted]  app
                                 index.html  906 bytes          [emitted]

**Comment by zhoubhin** [comment]
我也遇到这个提示，但似乎对最后打包没什么影响？

**Comment by sicmu** [comment]
我是新手，请求打包后，怎么部署，可以直接放到tomcat?

**Comment by sicmu** [comment]
确实放到tomcat就可以跑了。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by yuantingjun** [comment]
build/build.js 中
```
cp('-R', 'static/*', assetsPath)
```
本项目没有static文件夹，所以有提示信息。
用vue-cli生成的项目应该有个默认的static文件夹，本项目应该不是用vue-cli直接生成的项目
