### ISSUE TITLE
请问在根目录下有一个index.html 里面有<router-view></router-view>这个，在App.vue这个文件里面也有<router-view></router-view>

### ISSUE THREAD

**Issue by limeiyan1** [bailicangdu/vue2-happyfri#47]
请问在根目录下有一个index.html 里面有<router-view></router-view>这个，在App.vue这个文件里面也有<router-view></router-view>也有这个，为什么这2个文件都要有这句，我看vue-cli的项目只有在App.vue里面才有<router-view></router-view>。。麻烦解答下，谢谢

**Comment by bailicangdu** [comment]
版本不一样，新版没有了

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by yuantingjun** [comment]
这是嵌套路由
index.html 中的 router-view, 显示的是 App(/)，
App 中的 router-view 显示的是 home,item,score等子组件
将App修改为
```
<div>
    <h2 style="color: red;">app</h2>
    <router-view></router-view>
</div>
```
效果更明显
