### ISSUE TITLE
这个不能在windons下面运行吗

### ISSUE THREAD

**Issue by foreverOnTheWay** [bailicangdu/vue2-happyfri#5]

**Comment by baselin** [comment]
可以的

**Comment by GivenCui** [comment]
通过git clone的方式下载, 不要直接下载zip包解压, 可能是因为Ios系统和win系统的换行符不同导致的, git clone下载源码后会自动转换换行符, 我就遇到了这个问题

**Comment by consoleloghello** [comment]
window下面跑npm run dev 报错啊！有人window下跑起来的吗

**Comment by WanderLV** [comment]
npm run dev报错，一般都是node-sass安装不成功，用淘宝镜像安装node-sass后，在执行npm run dev，就Ok了

**Comment by yybgo** [comment]
安装了node-sassl,怎么npm run dev 报错

**Comment by hellowqw** [comment]
报错缺少模块，安装报错中所有的模块之后又说Error: Cannot find module 'webpack-core/lib/ReplaceSource'

**Comment by yuhang04210** [comment]
你把那个node_modules文件夹删除之后，cnpm install一下试试可以吗

**Comment by hellowqw** [comment]
可以啦！谢谢大神~ 还好有cnpm的存在，烦人的墙
