### ISSUE TITLE
config/index.html

### ISSUE THREAD

**Issue by c-yyy** [bailicangdu/vue2-happyfri#51]
`build: {assetsSubDirectory: 'static',
        assetsPublicPath: '/happyfri/',}`
and
`build: {assetsSubDirectory: 'static',
        assetsPublicPath: './',}`
都是`no such file or directory :static/* `
why?

**Comment by hekang123456** [comment]
我也想知道为什么啊

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
