### ISSUE TITLE
执行npm install 出现如下问题，本人新手 求解决方案

### ISSUE THREAD

**Issue by fedalee** [bailicangdu/vue2-happyfri#52]
$ npm install
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by fedalee** [comment]
网上说需要修改package.json文件    不知道这个是不是npm版本的原因导致的呢

**Comment by fedalee** [comment]
解决npm WARN deprecated babel-preset-es2015@6.24.1: 🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!警告

http://www.sohu.com/a/193955974_463970

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
