### ISSUE TITLE
在新项目下拷贝src，打开项目是这样的

### ISSUE THREAD

**Issue by xiaozhanghui** [bailicangdu/vue2-happyfri#53]
求指导，这是怎么回事
![image](https://user-images.githubusercontent.com/23646391/34732687-ee5a6586-f5a0-11e7-812a-7c019c1c731c.png)

  
![image](https://user-images.githubusercontent.com/23646391/34753881-83ad775a-f5f5-11e7-964f-a17d7c42fec6.png)
这个图片地址不对导致的或是图片后面没有那个随机数，为什么？还有为什么他又生成一个body标签上的，css中不是有吗？

**Comment by bailicangdu** [comment]
没看到代码我也不好猜

**Comment by xiaozhanghui** [comment]
![image](https://user-images.githubusercontent.com/23646391/34753867-6caeb956-f5f5-11e7-8eb1-4e2699fa466b.png)
这个图片地址不对

**Comment by xiaozhanghui** [comment]
大佬，我更新问题了，你看看

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
