### ISSUE TITLE
这个为什么不一样

### ISSUE THREAD

**Issue by xiaozhanghui** [bailicangdu/vue2-happyfri#54]
一个是抄的一个是你的
  
![u6p6qk1i p0 ejn a rc1 8](https://user-images.githubusercontent.com/23646391/34734968-b0a2190c-f5a8-11e7-942d-31f438ffe013.png)

![qq 20180110015209](https://user-images.githubusercontent.com/23646391/34735122-3dfb0250-f5a9-11e7-9f5b-09b75acea3c1.png)

初学者求指教

**Comment by bailicangdu** [comment]
脚手架版本不一样吧

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
