### ISSUE TITLE
Mutation 必须是同步函数

### ISSUE THREAD

**Issue by Neal-Caffrey** [bailicangdu/vue2-happyfri#56]
刚开始学Vue，请教一下，不知道对不对。我看文档上说：
现在想象，我们正在 debug 一个 app 并且观察 devtool 中的 mutation 日志。每一条 mutation 被记录，devtools 都需要捕捉到前一状态和后一状态的快照。然而，在上面的例子中 mutation 中的异步函数中的回调让这不可能完成：因为当 mutation 触发的时候，回调函数还没有被调用，devtools 不知道什么时候回调函数实际上被调用——实质上任何在回调函数中进行的状态的改变都是不可追踪的；
您代码里记录做题时间有这样写：
`	/*
	记录做题时间
	 */
	[REMBER_TIME](state) {
		state.timer = setInterval(() => {
			state.allTime++;
		}, 1000)
	},`
不知道这样有没有问题，请指教！

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by yuantingjun** [comment]
确实有问题，异步应该写到action中吧 @bailicangdu
