### ISSUE TITLE
开发环境下图片不能显示

### ISSUE THREAD

**Issue by wadecoding** [bailicangdu/vue2-happyfri#57]
你好，我在仿写这个项目的时候遇到了一个问题。我尝试了很久都没能搞清楚问题的原因。

- [x] 已查询过相关文档
- [x] 已上网做过相应查询
---

是这样的，我在模仿主页，在CSS和`created`钩子函数插入资源的时候遇到了问题，无论怎么改变图片的路径，它都不会在页面上显示。控制台没有错误信息输出

我认为这是`vue-loader`中的东西，于是查看了相关文档，但是文档上说有关`.png` `.jpg`的`file-loader`已经集成在环境中了。有关代码已经上传至[此处](https://github.com/wadecoding/Vue2OverAllStudy/tree/master/src)

另外，我还有个疑问想请教。在你给出的[代码](https://github.com/bailicangdu/vue2-happyfri/blob/master/src/components/itemcontainer.vue#L89)中第89行，为什么图片的路径是在static路径下，而源代码中不存在static这个文件夹。是当时的脚手架没有给出这个文件夹还是这个就是引入`webpack`打包好之后的静态资源文件

我的`Vue`和`Vue-CLI`版本是`2.9.1`，`webpack`版本是`3.6.0`

非常感谢你的帮助

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by yuantingjun** [comment]
1. .vue文件在编译过程中（vue-loader），所有的资源路径例如 &lt;img src="..."&gt;、background: url(...) 和 @import 会作为模块依赖,所以 template,style 中的路径是相对于开发目录（src）。
2. js中的document.body.style.backgroundImage = 'url(/static/img/1-1.jpg)'; 不会作为模块依赖，所以需写成构建后的路径
3. 图片构建位置为 static/img
```
assetsSubDirectory: 'static'           // config/index.js
utils.assetsPath('img/[name].[ext]')   // build/webpack.base.conf.js
exports.assetsPath = function(_path) { // build/utils.js
    var assetsSubDirectory = process.env.NODE_ENV === 'production' ? config.build.assetsSubDirectory : config.dev.assetsSubDirectory
    return path.posix.join(assetsSubDirectory, _path)
}
```
4. common.less中已经引用了 background: url(../images/1-1.jpg) no-repeat; 所以在js中可以使用1-1.jpg；否则图片将不会正常加载，因为没有作为依赖构建到static/img 目录下。
5. 在js中单独使用图片,先作为模块依赖加载，再使用
```
import img1 from '../images/1-1.jpg'
console.log(img1);//  /static/img/1-1.jpg
document.body.style.backgroundImage = 'url('+img1+')';
```
总结：
1. template/style中的图片资源默认作为模块依赖
2. js中通过style操作图片时，不作为模块依赖，要么明确依赖加载，要么写构建后的图片路径(必须在less中或别的js中已经依赖加载)
