### ISSUE TITLE
图片引用的地址问题

### ISSUE THREAD

**Issue by limeiyan1** [bailicangdu/vue2-happyfri#60]
为什么body标签的背景图片用的是happyfri/static/img下面的图片，而itemcontainer.vue里样式的背景图片的地址是images里面的图片

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by yuantingjun** [comment]
1. .vue文件在编译过程中（vue-loader），所有的资源路径例如 <img src="...">、background: url(...) 和 @import 会作为模块依赖,所以 template,style 中的路径是相对于开发目录（src）。
2. js中的document.body.style.backgroundImage = 'url(/static/img/1-1.jpg)'; 不会作为模块依赖，所以需写成构建后的路径
3. 图片构建位置为 static/img
    ```
    assetsSubDirectory: 'static'           // config/index.js
    utils.assetsPath('img/[name].[ext]')   // build/webpack.base.conf.js
    exports.assetsPath = function(_path) { // build/utils.js
        var assetsSubDirectory = process.env.NODE_ENV === 'production' ? config.build.assetsSubDirectory : config.dev.assetsSubDirectory
        return path.posix.join(assetsSubDirectory, _path)
    }
    ```
4. common.less中已经引用了 background: url(../images/1-1.jpg) no-repeat; 所以在js中可以使用1-1.jpg；否则图片将不会正常加载，因为没有作为依赖构建到static/img 目录下。
5. 在js中单独使用图片,先作为模块依赖加载，再使用
```
import img1 from '../images/1-1.jpg'
console.log(img1);//  /static/img/1-1.jpg
document.body.style.backgroundImage = 'url('+img1+')';
```
