### ISSUE TITLE
npm run dev就报错，无效启动项目啊

### ISSUE THREAD

**Issue by RM-Hwad** [bailicangdu/vue2-happyfri#68]
![image](https://user-images.githubusercontent.com/26077312/37814933-a468eb38-2ea7-11e8-892e-d133ccc43d65.png)

**Comment by yuantingjun** [comment]
端口占用
1. 通过 netstat -aon|findstr "8088" 查看端口占用
2. 查看PID对应的进程 tasklist|findstr "pid"
3. 结束进程 taskkill /f /t /im tor.exe
4. 重新 npm run dev

**Comment by Thlq** [comment]
换一个端口号
