### ISSUE TITLE
为什么只能移动端打开。web端打开不能使用。怎么不做成自适应的？

### ISSUE THREAD

**Issue by 65725738** [bailicangdu/vue2-happyfri#71]
为什么只能移动端打开。web端打开不能使用。怎么不做成自适应的？还有另一个模仿饿了吗的也一样

**Comment by yuantingjun** [comment]
rem.js 中 docEl.style.fontSize = 20 * (clientWidth / 320) + 'px';
这个方案设置html的font-size时，没有考虑 dpr，也有缺陷。
可以考虑手淘的flexible方案，如有更好的方案请告知
