### ISSUE TITLE
运行时自动打开浏览器应该如何配置呢

### ISSUE THREAD

**Issue by FromXTLeo** [bailicangdu/vue2-happyfri#72]
运行项目的时候 不能自动打开浏览器，我已经在config/index.js  里面配置autoOpenBrowser:true  但是还是不行，求指点

**Comment by yuantingjun** [comment]
if (process.env.NODE_ENV !== 'testing') {
        //opn(uri)
}
build/dev-server.js 第80行放开 opn(uri) 注释即可
