### ISSUE TITLE
图片路径问题

### ISSUE THREAD

**Issue by yuantingjun** [bailicangdu/vue2-happyfri#74]
```
document.body.style.backgroundImage = 'url(/static/img/1-1.jpg)';
background: url(../images/WechatIMG2.png) no-repeat;
<img src="../../images/4-4.png" height="212" width="212" class="code_img">
```
你好，请问为什么 
1. js中的图片路径是/static/img，而css,html中是 images/
2. css中的images/WechatIMG2.png 在构建时又是怎么转换为/static/img的 ？
谢谢

**Comment by bailicangdu** [comment]
这是由webpack配置的

**Comment by yuantingjun** [comment]
1. .vue文件在编译过程中（vue-loader），所有的资源路径例如 &lt;img src="..."&gt;、background: url(...) 和 @import 会作为模块依赖,所以 template,style 中的路径是相对于开发目录（src）。
2. js中的document.body.style.backgroundImage = 'url(/static/img/1-1.jpg)'; 不会作为模块依赖，所以需写成构建后的路径
3. 图片构建位置为 static/img
```
assetsSubDirectory: 'static'           // config/index.js
utils.assetsPath('img/[name].[ext]')   // build/webpack.base.conf.js
exports.assetsPath = function(_path) { // build/utils.js
    var assetsSubDirectory = process.env.NODE_ENV === 'production' ? config.build.assetsSubDirectory : config.dev.assetsSubDirectory
    return path.posix.join(assetsSubDirectory, _path)
}
```
4. common.less中已经引用了 background: url(../images/1-1.jpg) no-repeat; 所以在js中可以使用1-1.jpg；否则图片将不会正常加载，因为没有作为依赖构建到static/img 目录下。
5. 在js中单独使用图片,先作为模块依赖加载，再使用
```
import img1 from '../images/1-1.jpg'
console.log(img1);//  /static/img/1-1.jpg
document.body.style.backgroundImage = 'url('+img1+')';
```
总结：
1. template/style中的图片资源默认作为模块依赖
2. js中通过style操作图片时，不作为模块依赖，要么明确依赖加载，要么写构建后的图片路径(必须在less中或别的js中已经依赖加载)
