### ISSUE TITLE
有的loader多余了吗

### ISSUE THREAD

**Issue by WHITE-ILMARE** [bailicangdu/vue2-happyfri#77]
在webpack.base.config.js中，有这么一项{
            test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
            loader: 'url',
            query: {
                limit: 10000,
                name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
            }
但整个项目中并没有这样后缀的资源文件啊，这个loader是不是多余了。还是说不管有没有，这些loader加上去总没有错。

**Comment by bailicangdu** [comment]
多多益善

**Comment by WHITE-ILMARE** [comment]
了然

**Comment by MinosIE** [comment]
根据实际情况取舍
