### ISSUE TITLE
mutations中方法定义方式 为什么要用类似数组形式调用

### ISSUE THREAD

**Issue by zbw7415604** [bailicangdu/vue2-happyfri#80]
mutations.js中先定义：const ADD_ITEMNUM = 'ADD_ITEMNUM'
然后后面再用 方括号括起来调用 是什么用意 ？方便修改么，求解
	//点击进入下一题
	[ADD_ITEMNUM](state, num) {
		state.itemNum += num;
	}

**Comment by SteadyArcticFox** [comment]
同样没明白，没见过这个语法啊，函数定义还可以这样的吗？
