### ISSUE TITLE
render问题

### ISSUE THREAD

**Issue by 870714234** [bailicangdu/vue2-happyfri#83]
在main.js中，我在别的书中看到的需要添加render才能渲染出页面，但是您这里并没有看到有render。是在别的地方用其他东西替代了么？刚开始学vue，不是很懂，希望您指点一下，谢谢

**Comment by hp0844182** [comment]
如果 Vue 实例在实例化时没有收到 el 选项，则它处于“未挂载”状态，没有关联的 DOM 元素。可以使用 vm.$mount() 手动地挂载一个未挂载的实例。
